epochs: 10

flow:
    transformer: torchnf.transformers.AffineTransform
    net_hidden_shape: [16, 32, 64, 32, 16]
    net_activation: torch.nn.LeakyReLU
    net_final_activation: torch.nn.Tanh
    depth: 12

moons:
    total_size: 6400
    batch_size: 32
    noise: 0.1
    train_frac: 0.75
