name: Build and Deploy Docs

on:
  push:
    branches:
      - main

permissions: 
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.9'
        
      - name: Install and Build 🔧
        run: |
          python -m pip install --upgrade pip
          pip install tox
          tox -e docs
        
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4.3.3
        with:
          branch: gh-pages
          folder: docs/_build/html
